'use server'

import { auth } from '@clerk/nextjs/server'
import { revalidatePath } from 'next/cache'
import { prisma } from '@/lib/prisma'
import { logAudit } from '@/lib/audit'
import { z } from 'zod'
import { Decimal } from '@prisma/client/runtime/library'

// Types
export type WebsiteType = 'GENERAL' | 'SCHOOL' | 'COURSE' | 'PORTFOLIO'

async function getOrganization() {
  const { userId, orgId } = await auth()
  if (!userId || !orgId) {
    throw new Error('Unauthorized')
  }
  let org = await prisma.organization.findUnique({
    where: { clerkOrgId: orgId }
  })
  if (!org) {
    org = await prisma.organization.create({
      data: {
        clerkOrgId: orgId,
        name: 'My Organization',
        slug: orgId.toLowerCase().replace(/[^a-z0-9]/g, '-'),
      }
    })
  }
  return { userId, orgId: org.id }
}

// Schemas
const createWebsiteSchema = z.object({
  name: z.string().min(1),
  slug: z.string().min(1).regex(/^[a-z0-9-]+$/),
  description: z.string().nullable().optional(),
  type: z.enum(['GENERAL', 'SCHOOL', 'COURSE', 'PORTFOLIO']).default('GENERAL'),
  primaryColor: z.string().default('#3B82F6'),
  secondaryColor: z.string().default('#10B981'),
  fontFamily: z.string().default('sans'),
})

export async function getWebsites() {
  const { orgId } = await getOrganization()
  return prisma.website.findMany({
    where: { organizationId: orgId },
    orderBy: { createdAt: 'desc' },
    include: {
      pages: {
        select: { id: true, title: true, slug: true }
      },
      _count: {
        select: { submissions: true, courses: true }
      }
    }
  })
}

export async function getWebsite(id: string) {
  const { orgId } = await getOrganization()
  return prisma.website.findFirst({
    where: { id, organizationId: orgId },
    include: {
      pages: {
        orderBy: { slug: 'asc' },
        include: {
          sections: {
            orderBy: { sortOrder: 'asc' }
          }
        }
      },
      courses: {
        include: {
          lessons: {
            orderBy: { sortOrder: 'asc' }
          }
        }
      },
      submissions: {
        orderBy: { createdAt: 'desc' }
      }
    }
  })
}

export async function createWebsite(input: z.infer<typeof createWebsiteSchema>) {
  const { userId, orgId } = await getOrganization()
  const validated = createWebsiteSchema.parse(input)

  const website = await prisma.website.create({
    data: {
      ...validated,
      organizationId: orgId,
      createdBy: userId,
      headerConfig: JSON.stringify({
        logo: validated.name,
        links: [
          { label: 'Home', url: '/' },
          { label: 'About', url: '/about' },
          { label: 'Contact', url: '/contact' }
        ]
      }),
      footerConfig: JSON.stringify({
        copyright: `© ${new Date().getFullYear()} ${validated.name}. All rights reserved.`
      })
    }
  })

  // Create default homepage
  await prisma.webPage.create({
    data: {
      websiteId: website.id,
      title: 'Home',
      slug: 'home',
      sections: {
        create: [
          {
            type: 'HERO',
            sortOrder: 0,
            content: JSON.stringify({
              title: `Welcome to ${website.name}`,
              subtitle: 'Create something amazing today. Beautiful designs generated by AI.',
              ctaText: 'Get Started',
              ctaUrl: '/contact',
              bgImage: ''
            })
          }
        ]
      }
    }
  })

  await logAudit({ organizationId: orgId, userId, action: 'CREATE', entityType: 'Website', entityId: website.id, newValues: website as any })
  revalidatePath('/dashboard/website-builder')
  return website
}

export async function updateWebsite(id: string, data: any) {
  const { userId, orgId } = await getOrganization()
  const existing = await prisma.website.findFirst({ where: { id, organizationId: orgId } })
  if (!existing) throw new Error('Website not found')

  const website = await prisma.website.update({
    where: { id },
    data: {
      name: data.name,
      description: data.description,
      primaryColor: data.primaryColor,
      secondaryColor: data.secondaryColor,
      fontFamily: data.fontFamily,
      customCss: data.customCss,
      headerConfig: data.headerConfig,
      footerConfig: data.footerConfig,
      paymentProvider: data.paymentProvider,
      stripePublicKey: data.stripePublicKey,
      stripeSecretKey: data.stripeSecretKey,
      paystackPublicKey: data.paystackPublicKey,
      paystackSecretKey: data.paystackSecretKey,
      lemonSqueezyApiKey: data.lemonSqueezyApiKey,
      lemonSqueezyStoreId: data.lemonSqueezyStoreId,
    }
  })

  await logAudit({ organizationId: orgId, userId, action: 'UPDATE', entityType: 'Website', entityId: id, oldValues: existing as any, newValues: website as any })
  revalidatePath(`/dashboard/website-builder/${id}/editor`)
  return website
}

export async function deleteWebsite(id: string) {
  const { userId, orgId } = await getOrganization()
  const existing = await prisma.website.findFirst({ where: { id, organizationId: orgId } })
  if (!existing) throw new Error('Website not found')

  await prisma.website.delete({ where: { id } })
  await logAudit({ organizationId: orgId, userId, action: 'DELETE', entityType: 'Website', entityId: id, oldValues: existing as any })
  revalidatePath('/dashboard/website-builder')
  return { success: true }
}

// Pages
export async function createWebPage(websiteId: string, title: string, slug: string) {
  const { userId, orgId } = await getOrganization()
  const website = await prisma.website.findFirst({ where: { id: websiteId, organizationId: orgId } })
  if (!website) throw new Error('Website not found')

  const sanitizedSlug = slug.toLowerCase().replace(/[^a-z0-9-]/g, '-')
  const page = await prisma.webPage.create({
    data: {
      websiteId,
      title,
      slug: sanitizedSlug,
      sections: {
        create: [
          {
            type: 'HERO',
            sortOrder: 0,
            content: JSON.stringify({
              title: title,
              subtitle: `Welcome to the ${title} page.`,
              ctaText: 'Learn More',
              ctaUrl: '/'
            })
          }
        ]
      }
    }
  })

  revalidatePath(`/dashboard/website-builder/${websiteId}/editor`)
  return page
}

export async function deleteWebPage(id: string) {
  const { userId, orgId } = await getOrganization()
  const page = await prisma.webPage.findUnique({
    where: { id },
    include: { website: true }
  })
  if (!page || page.website.organizationId !== orgId) {
    throw new Error('Page not found')
  }
  if (page.slug === 'home') {
    throw new Error('Cannot delete homepage')
  }

  await prisma.webPage.delete({ where: { id } })
  revalidatePath(`/dashboard/website-builder/${page.websiteId}/editor`)
  return { success: true }
}

// Sections
export async function addWebSection(pageId: string, type: string, content: string, styles?: string) {
  const { orgId } = await getOrganization()
  const page = await prisma.webPage.findUnique({
    where: { id: pageId },
    include: { website: true }
  })
  if (!page || page.website.organizationId !== orgId) {
    throw new Error('Page not found')
  }

  const lastSection = await prisma.webSection.findFirst({
    where: { pageId },
    orderBy: { sortOrder: 'desc' }
  })
  const nextOrder = lastSection ? lastSection.sortOrder + 1 : 0

  const section = await prisma.webSection.create({
    data: {
      pageId,
      type,
      sortOrder: nextOrder,
      content,
      styles: styles || '{}'
    }
  })

  revalidatePath(`/dashboard/website-builder/${page.websiteId}/editor`)
  return section
}

export async function updateWebSection(id: string, content: string, styles?: string) {
  const { orgId } = await getOrganization()
  const section = await prisma.webSection.findUnique({
    where: { id },
    include: { page: { include: { website: true } } }
  })
  if (!section || section.page.website.organizationId !== orgId) {
    throw new Error('Section not found')
  }

  const updated = await prisma.webSection.update({
    where: { id },
    data: {
      content,
      styles: styles || section.styles
    }
  })

  revalidatePath(`/dashboard/website-builder/${section.page.websiteId}/editor`)
  return updated
}

export async function deleteWebSection(id: string) {
  const { orgId } = await getOrganization()
  const section = await prisma.webSection.findUnique({
    where: { id },
    include: { page: { include: { website: true } } }
  })
  if (!section || section.page.website.organizationId !== orgId) {
    throw new Error('Section not found')
  }

  await prisma.webSection.delete({ where: { id } })
  revalidatePath(`/dashboard/website-builder/${section.page.websiteId}/editor`)
  return { success: true }
}

export async function updateSectionOrder(sectionIds: string[]) {
  const { orgId } = await getOrganization()
  if (sectionIds.length === 0) return

  const firstSection = await prisma.webSection.findUnique({
    where: { id: sectionIds[0] },
    include: { page: { include: { website: true } } }
  })
  if (!firstSection || firstSection.page.website.organizationId !== orgId) {
    throw new Error('Unauthorized')
  }

  // Update order in database transaction
  await prisma.$transaction(
    sectionIds.map((id, index) =>
      prisma.webSection.update({
        where: { id },
        data: { sortOrder: index }
      })
    )
  )

  revalidatePath(`/dashboard/website-builder/${firstSection.page.websiteId}/editor`)
}

// Form Submission handling
export async function submitWebForm(websiteId: string, formType: string, payload: string) {
  const submission = await prisma.formSubmission.create({
    data: {
      websiteId,
      formType,
      payload,
      isRead: false
    }
  })
  return submission
}

export async function markSubmissionRead(id: string) {
  const { orgId } = await getOrganization()
  const submission = await prisma.formSubmission.findUnique({
    where: { id },
    include: { website: true }
  })
  if (!submission || submission.website.organizationId !== orgId) {
    throw new Error('Submission not found')
  }

  await prisma.formSubmission.update({
    where: { id },
    data: { isRead: true }
  })

  revalidatePath(`/dashboard/website-builder/${submission.websiteId}/submissions`)
}

// Elearning Actions
export async function createWebCourse(websiteId: string, data: { title: string; slug: string; description: string; price: number }) {
  const { orgId } = await getOrganization()
  const website = await prisma.website.findFirst({ where: { id: websiteId, organizationId: orgId } })
  if (!website) throw new Error('Website not found')

  const course = await prisma.webCourse.create({
    data: {
      websiteId,
      title: data.title,
      slug: data.slug.toLowerCase().replace(/[^a-z0-9-]/g, '-'),
      description: data.description,
      price: new Decimal(data.price),
      isPublished: true
    }
  })

  revalidatePath(`/dashboard/website-builder/${websiteId}/editor`)
  return course
}

export async function createWebLesson(courseId: string, data: { title: string; slug: string; content: string; videoUrl?: string; isFree: boolean }) {
  const { orgId } = await getOrganization()
  const course = await prisma.webCourse.findUnique({
    where: { id: courseId },
    include: { website: true }
  })
  if (!course || course.website.organizationId !== orgId) {
    throw new Error('Course not found')
  }

  const lastLesson = await prisma.webLesson.findFirst({
    where: { courseId },
    orderBy: { sortOrder: 'desc' }
  })
  const nextOrder = lastLesson ? lastLesson.sortOrder + 1 : 0

  const lesson = await prisma.webLesson.create({
    data: {
      courseId,
      title: data.title,
      slug: data.slug.toLowerCase().replace(/[^a-z0-9-]/g, '-'),
      content: data.content,
      videoUrl: data.videoUrl,
      isFree: data.isFree,
      sortOrder: nextOrder
    }
  })

  revalidatePath(`/dashboard/website-builder/${course.websiteId}/editor`)
  return lesson
}

// AI & Mock Website Generation
export async function generateWebsiteWithAI(prompt: string, type: WebsiteType) {
  const { userId, orgId } = await getOrganization()
  
  // Format slug safely
  const rawSlug = prompt.toLowerCase().replace(/[^a-z0-9\s-]/g, '').trim().replace(/\s+/g, '-')
  const slugSuffix = Math.floor(1000 + Math.random() * 9000)
  const slug = `${rawSlug.slice(0, 15)}-${slugSuffix}`

  // Create website record
  const name = prompt.length > 30 ? `${prompt.slice(0, 30)}...` : prompt

  // Custom colors and settings based on type
  let primaryColor = '#3B82F6' // Blue
  let secondaryColor = '#10B981' // Green
  let fontFamily = 'sans'

  if (type === 'SCHOOL') {
    primaryColor = '#1E3A8A' // Navy
    secondaryColor = '#D97706' // Amber
    fontFamily = 'outfit'
  } else if (type === 'COURSE') {
    primaryColor = '#7C3AED' // Violet
    secondaryColor = '#F59E0B' // Amber
    fontFamily = 'inter'
  } else if (type === 'PORTFOLIO') {
    primaryColor = '#EC4899' // Pink
    secondaryColor = '#6366F1' // Indigo
    fontFamily = 'outfit'
  }

  const website = await prisma.website.create({
    data: {
      name,
      slug,
      description: `Generated by AI for: "${prompt}"`,
      type,
      primaryColor,
      secondaryColor,
      fontFamily,
      organizationId: orgId,
      createdBy: userId,
      headerConfig: JSON.stringify({
        logo: name.toUpperCase(),
        links: [
          { label: 'Home', url: '/' },
          { label: 'About', url: '/about' },
          { label: 'Contact', url: '/contact' },
          ...(type === 'COURSE' ? [{ label: 'Courses', url: '/courses' }] : []),
          ...(type === 'SCHOOL' ? [{ label: 'Admissions', url: '/admissions' }] : [])
        ]
      }),
      footerConfig: JSON.stringify({
        copyright: `© ${new Date().getFullYear()} ${name}. Designed for education and community growth.`
      })
    }
  })

  // Try to use live Gemini API if available, else run detailed High-Fidelity Mock Generator
  let pagesData: Array<{ title: string; slug: string; sections: Array<{ type: string; content: any }> }> = []

  const hasGeminiKey = !!process.env.GEMINI_API_KEY
  if (hasGeminiKey) {
    try {
      const response = await fetch(
        `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${process.env.GEMINI_API_KEY}`,
        {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            contents: [{
              parts: [{
                text: `Generate website pages structure for type "${type}" based on description: "${prompt}".
                Output strictly a JSON array of pages with their sections. Do not include markdown code block formatting.
                Format:
                [
                  {
                    "title": "Home",
                    "slug": "home",
                    "sections": [
                      { "type": "HERO", "content": { "title": "Heading", "subtitle": "Subtext", "ctaText": "Button", "ctaUrl": "/contact" } }
                    ]
                  }
                ]`
              }]
            }],
            generationConfig: {
              responseMimeType: 'application/json'
            }
          })
        }
      )
      const data = await response.json()
      const text = data.candidates?.[0]?.content?.parts?.[0]?.text
      if (text) {
        pagesData = JSON.parse(text)
      }
    } catch (e) {
      console.error('Gemini API call failed, falling back to mock generator', e)
    }
  }

  // High-Fidelity Mock generator Fallback
  if (pagesData.length === 0) {
    if (type === 'SCHOOL') {
      pagesData = [
        {
          title: 'Home',
          slug: 'home',
          sections: [
            {
              type: 'HERO',
              content: {
                title: 'St. Jude Academy of Excellence',
                subtitle: 'Nurturing leadership, intellect, and character for the leaders of tomorrow.',
                ctaText: 'Apply for Admission',
                ctaUrl: '/admissions',
                bgImage: 'https://images.unsplash.com/photo-1546410531-bb4caa6b424d?q=80&w=1200'
              }
            },
            {
              type: 'FEATURES',
              content: {
                title: 'Why Choose St. Jude?',
                subtitle: 'We offer an integrated curriculum designed for academic rigour and creative growth.',
                items: [
                  { title: 'Global Curriculum', desc: 'Prepares students for international university entries.' },
                  { title: 'Modern Facilities', desc: 'State-of-the-art labs, sports courts, and digital library.' },
                  { title: 'Creative Arts', desc: 'Award-winning programs in drama, music, and painting.' }
                ]
              }
            },
            {
              type: 'TESTIMONIALS',
              content: {
                title: 'What Parents Say',
                items: [
                  { quote: 'The digital resources and supportive teaching team at St. Jude transformed my son\'s approach to learning.', author: 'Mrs. Sarah Ouko, Parent' }
                ]
              }
            }
          ]
        },
        {
          title: 'About Us',
          slug: 'about',
          sections: [
            {
              type: 'HERO',
              content: {
                title: 'Our Vision & Mission',
                subtitle: 'Founded in 2012, St. Jude is committed to holistic learning that builds global citizenship.',
                ctaText: 'Contact Us',
                ctaUrl: '/contact'
              }
            },
            {
              type: 'RICH_TEXT',
              content: {
                title: 'Message from the Principal',
                body: 'Welcome to St. Jude! Our educational ecosystem is built on transparency, innovation, and care. We encourage parents to be active partners in their child\'s educational voyage.'
              }
            }
          ]
        },
        {
          title: 'Admissions',
          slug: 'admissions',
          sections: [
            {
              type: 'HERO',
              content: {
                title: 'Admissions & Enrollment',
                subtitle: 'Secure a place for your child for the upcoming academic year.',
                ctaText: 'Register Today',
                ctaUrl: '#form'
              }
            },
            {
              type: 'CONTACT_FORM',
              content: {
                title: 'Admission Inquiry Form',
                subtitle: 'Submit this form and our registrar will get in touch with you.',
                buttonText: 'Submit Inquiry',
                formType: 'ADMISSION'
              }
            }
          ]
        },
        {
          title: 'Contact',
          slug: 'contact',
          sections: [
            {
              type: 'CONTACT_FORM',
              content: {
                title: 'Get In Touch',
                subtitle: 'Have a question? Write to us directly.',
                buttonText: 'Send Message',
                formType: 'CONTACT'
              }
            }
          ]
        }
      ]
    } else if (type === 'COURSE') {
      pagesData = [
        {
          title: 'Home',
          slug: 'home',
          sections: [
            {
              type: 'HERO',
              content: {
                title: 'Master Modern Coding Skills',
                subtitle: 'Acquire practical skills from expert tutors in Full Stack Development, UX Design, and Product Management.',
                ctaText: 'Browse Courses',
                ctaUrl: '/courses',
                bgImage: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?q=80&w=1200'
              }
            },
            {
              type: 'FEATURES',
              content: {
                title: 'Learn at Your Own Pace',
                subtitle: 'Designed for professionals with busy schedules.',
                items: [
                  { title: 'Interactive Quizzes', desc: 'Verify your learning step-by-step with practical assignments.' },
                  { title: 'Peer Community', desc: 'Collaborate and network with hundreds of fellow students.' },
                  { title: 'Certificate of Honor', desc: 'Boost your LinkedIn profile with industry-recognized badges.' }
                ]
              }
            }
          ]
        },
        {
          title: 'Courses',
          slug: 'courses',
          sections: [
            {
              type: 'HERO',
              content: {
                title: 'Our Interactive Catalog',
                subtitle: 'Unlock professional mastery with direct access to lessons and assessments.',
                ctaText: 'View Details',
                ctaUrl: '#catalog'
              }
            },
            {
              type: 'COURSE_GRID',
              content: {
                title: 'Featured Bootcamps',
                subtitle: 'Choose a program to launch your new career.'
              }
            }
          ]
        },
        {
          title: 'Contact Us',
          slug: 'contact',
          sections: [
            {
              type: 'CONTACT_FORM',
              content: {
                title: 'Questions about our Bootcamps?',
                subtitle: 'Fill out this form and a student advisor will contact you within 24 hours.',
                buttonText: 'Request Info',
                formType: 'CONTACT'
              }
            }
          ]
        }
      ]

      // Pre-create mock courses & lessons
      await prisma.webCourse.create({
        data: {
          websiteId: website.id,
          title: 'Full Stack Web Development',
          slug: 'full-stack-web-development',
          description: 'Learn HTML, CSS, JavaScript, Next.js, and Prisma from absolute scratch.',
          price: new Decimal(299.00),
          isPublished: true,
          lessons: {
            create: [
              { title: 'Introduction to HTML5', slug: 'intro-to-html5', content: 'In this lesson, we will explore HTML structure, tags, and semantic elements.', isFree: true, sortOrder: 0 },
              { title: 'Modern Styling with CSS', slug: 'modern-css', content: 'Learn Grid, Flexbox, and HSL colors for layout consistency.', isFree: false, sortOrder: 1 }
            ]
          }
        }
      })

      await prisma.webCourse.create({
        data: {
          websiteId: website.id,
          title: 'UX/UI Design Bootcamp',
          slug: 'ux-ui-design',
          description: 'Master Figma wireframes, interactive prototypes, and design systems.',
          price: new Decimal(199.00),
          isPublished: true,
          lessons: {
            create: [
              { title: 'Figma Basics', slug: 'figma-basics', content: 'Explore the Figma workspace, shapes, constraints, and grids.', isFree: true, sortOrder: 0 }
            ]
          }
        }
      })
    } else {
      // General/Portfolio Website Mock
      pagesData = [
        {
          title: 'Home',
          slug: 'home',
          sections: [
            {
              type: 'HERO',
              content: {
                title: 'Innovative Software Architecture',
                subtitle: 'Building reliable, high-performance distributed systems for scale.',
                ctaText: 'Hire Me',
                ctaUrl: '/contact',
                bgImage: 'https://images.unsplash.com/photo-1488590528505-98d2b5aba04b?q=80&w=1200'
              }
            },
            {
              type: 'FEATURES',
              content: {
                title: 'My Expertise',
                subtitle: 'Providing scalable backend systems and dynamic reactive frontend apps.',
                items: [
                  { title: 'Next.js & React', desc: 'Highly optimized page load times and server actions.' },
                  { title: 'System Design', desc: 'Secure PostgreSQL database structures and microservices.' }
                ]
              }
            }
          ]
        },
        {
          title: 'Contact',
          slug: 'contact',
          sections: [
            {
              type: 'CONTACT_FORM',
              content: {
                title: 'Start a Project',
                subtitle: 'Let\'s collaborate on building your next software solution.',
                buttonText: 'Send Inquiry',
                formType: 'CONTACT'
              }
            }
          ]
        }
      ]
    }
  }

  // Create pages and sections in the database
  for (const pageItem of pagesData) {
    await prisma.webPage.create({
      data: {
        websiteId: website.id,
        title: pageItem.title,
        slug: pageItem.slug,
        sections: {
          create: pageItem.sections.map((sec, idx) => ({
            type: sec.type,
            sortOrder: idx,
            content: JSON.stringify(sec.content),
            styles: '{}'
          }))
        }
      }
    })
  }

  await logAudit({ organizationId: orgId, userId, action: 'CREATE', entityType: 'Website', entityId: website.id, newValues: website as any })
  revalidatePath('/dashboard/website-builder')
  return website
}
